---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controlcenter-tls
  namespace: kafka
spec:
  secretName: controlcenter-tls
  dnsNames:
    - controlcenter.mochi.platform.dspdemos.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
